apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: my-registry/my-flask-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
            # Add other environment variables as needed
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api
spec:
  selector:
    app: flask-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: example.com # Replace with your domain name
      http:
        paths:
          - path: /flask-api
            pathType: Prefix
            backend:
              service:
                name: flask-api
                port:
                  name: http
  tls:
    - hosts:
        - example.com # Replace with your domain name
      secretName: tls-secret # Replace with the name of your TLS secret
