openapi: "3.0.0"
info:
  title: Flask API Example
  description: An example Flask API with Swagger documentation
  version: "1.0.0"

paths:
  /hello:
    get:
      summary: Returns a greeting message
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!

  /add:
    get:
      summary: Returns the sum of two numbers
      parameters:
        - in: query
          name: a
          required: true
          schema:
            type: integer
            example: 2
          description: The first number to add
        - in: query
          name: b
          required: true
          schema:
            type: integer
            example: 3
          description: The second number to add
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                    example: 5
